### ISSUE TITLE
About Adaptive EKF

### ISSUE THREAD

**Issue by ajaybhatt003** [prashanthr05/Adaptive-EKF-tests#1]
Hey I want to work on adaptive EKF where Q (process covariance)  and R (measurement covariance) are my parameters. I have range only sensor by which I need to location my ground robot. My problem with range data is that sometimes I get outliers which I can remove or basically provide high R while running EKF.
Kindly if have any basic adaptive EKF matlab code with you for getting started then please share with me.
Thanks

**Comment by prashanthr05** [comment]
Hi Ajay,
I do not have an implementation for online adaptive estimation of Q and R matrices. In this code, I had assumed values for these matrices and had passed model parameters (like stiffness and damping parameters) into a dual and joint estimation filter. For these filters, I just modified a previously available kalman filter code, which can be found in the folder **EKF/utils/ekf** 
You could follow this text for the details and it also has a section for variance estimation.
[Ch5 Dual Extended Kalman Filter Methods.pdf](https://github.com/prashanthr05/Adaptive-EKF-tests/files/1234081/Ch5.Dual.Extended.Kalman.Filter.Methods.pdf)

**Comment by prashanthr05** [comment]
Here's the link to the details of the EKF toolbox I used.
http://becs.aalto.fi/en/research/bayes/ekfukf/
